

export const COIN_LIST = [
    {
        COIN_ID: 1,
        COIN_BIP_44_INDEX:"0",
        COIN_NAME: 'Bitcoin',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://s2.coinmarketcap.com/static/img/coins/32x32/1.png?_=cb31027',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 2,
        COIN_BIP_44_INDEX:"2",
        COIN_NAME: 'Litecoin',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35309662/ltc.png',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 3,
        COIN_BIP_44_INDEX:"3",
        COIN_NAME: 'Dogecoin',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/19684/doge.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 4,
        COIN_BIP_44_INDEX:"5",
        COIN_NAME: 'Dash',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/33842920/dash.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 5,
        COIN_BIP_44_INDEX:"20",
        COIN_NAME: 'Digibyte',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/12318264/7638-nty_400x400.jpg?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 6,
        COIN_BIP_44_INDEX:"42",
        COIN_NAME: 'Decred',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/1382607/decred.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 7,
        COIN_BIP_44_INDEX:"43",
        COIN_NAME: 'Nem',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 8,
        COIN_BIP_44_INDEX:"77",
        COIN_NAME: 'Verge',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/12318032/xvg.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 9,
        COIN_BIP_44_INDEX:"81",
        COIN_NAME: 'Potcoin',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35651003/pot.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 10,
        COIN_BIP_44_INDEX:"128",
        COIN_NAME: 'Monero',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/19969/xmr.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 11,
        COIN_BIP_44_INDEX:"133",
        COIN_NAME: 'Zcash',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/351360/zec.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 12,
        COIN_BIP_44_INDEX:"134",
        COIN_NAME: 'Lisk',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/27011060/lsk.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 13,
        COIN_BIP_44_INDEX:"135",
        COIN_NAME: 'Steem',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/350907/steem.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 14,
        COIN_BIP_44_INDEX:"141",
        COIN_NAME: 'Komodo',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35651353/komodo300x300.jpg?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 15,
        COIN_BIP_44_INDEX:"144",
        COIN_NAME: 'Ripple',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/34477776/xrp.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 16,
        COIN_BIP_44_INDEX:"145",
        COIN_NAME: 'Bitcoin Cash',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35650680/bch.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 17,
        COIN_BIP_44_INDEX:"147",
        COIN_NAME: 'ZClassic',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35650715/zcl.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 18,
        COIN_BIP_44_INDEX:"148",
        COIN_NAME: 'Stellar Lumens',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://dynamic-assets.coinbase.com/ddaf9d27a2388105c5568c68ebe4078d057efac1cb9b091af6a57f4d187cf06b2701b95f75bd148d3872df32b69ebb678de71a42da317370aaec7d6448bda379/asset_icons/80782fe2d690f299e7f5bb9b89af87e1db75769e59c14fa0257054c962401805.png',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
   
    {
        COIN_ID: 19,
        COIN_BIP_44_INDEX:"175",
        COIN_NAME: 'Ravencoin',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/27011010/rvn.jpg?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 20,
        COIN_BIP_44_INDEX:"194",
        COIN_NAME: 'Eos',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/1383652/eos_1.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 21,
        COIN_BIP_44_INDEX:"195",
        COIN_NAME: 'Tron',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/34477805/trx.jpg?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 22,
        COIN_BIP_44_INDEX:"415",
        COIN_NAME: 'Electroneum',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/14761932/electroneum.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 23,
        COIN_BIP_44_INDEX:"714",
        COIN_NAME: 'Binance',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/9350818/binance.png',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 24,
        COIN_BIP_44_INDEX:"818",
        COIN_NAME: 'Vechain',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/12318129/ven.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 25,
        COIN_BIP_44_INDEX:"25",
        COIN_NAME: 'Neo',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/1383858/neo.jpg?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 26,
        COIN_BIP_44_INDEX:"1729",
        COIN_NAME: 'Tezos',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35651213/tezos-logo.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 27,
        COIN_BIP_44_INDEX:"1815",
        COIN_NAME: 'Cardano',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/12318177/ada.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 28,
        COIN_BIP_44_INDEX:"5741564",
        COIN_NAME: 'Waves',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/27010639/waves2.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 29,
        COIN_BIP_44_INDEX:"61",
        COIN_NAME: 'Ethereum Classic',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/33752295/etc_new.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    
   
    {
        COIN_ID: 30,
        COIN_BIP_44_INDEX:"60",
        COIN_NAME: 'ETH',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/20646/eth_logo.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 31,
        COIN_BIP_44_INDEX:"",
        COIN_NAME: 'Vegawallet (VGW) ',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://etherscan.io/token/images/vegawallettoken_28.png',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"5",
        COIN_ADDRESS:"",
    },
   
    {
        COIN_ID: 32,
        COIN_BIP_44_INDEX:"",
        COIN_NAME: '0x (ZRX) ',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/1383799/zrx.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"18",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 33,
        COIN_BIP_44_INDEX:"",
        COIN_NAME: 'Maker (MKR) ',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/1382296/mkr.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"18",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 34,
        COIN_BIP_44_INDEX:"",
        COIN_NAME: ' Tether (USDT) ERC20',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/1383672/usdt.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"6",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 35,
        COIN_BIP_44_INDEX:"",
        COIN_NAME: 'USD Coin (USDC)',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/34835941/usdc.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"6",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 36,
        COIN_BIP_44_INDEX:"https://www.cryptocompare.com/media/34478493/coinbase.png",
        COIN_NAME: 'Coinbase',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"18",
        COIN_ADDRESS:"",
    },
    {
        COIN_ID: 37,
        COIN_BIP_44_INDEX:"",
        COIN_NAME: 'ChainLink',
        COIN_NETWORK: 'MAINNET',
        COIN_LOGO:'https://www.cryptocompare.com/media/35309382/link.png?width=200',
        COIN_BALANCE_API:'',
        COIN_TRANSACTION_HISTORY_API:"",
        COIN_MARKET_PRICE_API:"",
        COIN_TRANSFER_API :"",
        COIN_DECIMALS:"18",
        COIN_ADDRESS:"",
    },
   
]