export const COIN_CONSTANTS ={
    GET_COIN_NAME:'GET_COIN_NAME',
    GET_COIN_DISPLAY_NAME:'GET_COIN_DISPLAY_NAME',
    GET_PUBLIC_KEY:'GET_PUBLIC_KEY',
    GET_PRIVATE_KEY:'GET_PRIVATE_KEY',
    GET_COIN_BALANCE:'GET_COIN_BALANCE',
    GET_COIN_LOGO:'GET_COIN_LOGO',
    GET_COIN_ADDRESS_LIST:'GET_COIN_ADDRESS_LIST'
    
}