export const WALLET_CONSTANTS ={
    GET_PASSPHRASE:'GET_PASSPHRASE',
    CREATE_PASSPHRASE:'CREATE_PASSPHRASE',
    HIDE_PASSPHRASE:'HIDE_PASSPHRASE',
    CHANGE_SEND_COIN_TYPE:'CHANGE_SEND_COIN_TYPE',
    SET_SENDMONEY:'SET_SENDMONEY',
    SET_SEND_ADDRESS: 'SET_SEND_ADDRESS',
    COPY_ADDRESS: 'COPY_ADDRESS',
    SET_COIN_NUMBER:'SET_COIN_NUMBER'
}